config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'inventories#index'
  devise_for :accounts
  resources :inventories
  resources :brands, only: %i[index destroy]
  resources :models, only: [:destroy]
  post 'brands/create'
  patch 'brands/update'
  post 'models/create'
  patch 'models/update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/brand_models/_brand_edit_form.html.erb
<%= form_with url: brand_models_update_brand_path, method: :post do |form| %>

  <div class="row mb-4">
    <div class="field form-group col">
      <%= form.label :id, "Old Brand Name", class: "form-label" %>
      <%= form.collection_select :id, Brand.order(:name), :id, :name, {}, {class: "form-control"} %>
    </div>

    <div class="field form-group col">
      <%= form.label :new_name, "New Brand Name", class: "form-label" %>
      <%= form.text_field :new_name, class: "form-control" %>
    </div>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-primary", value: "Save" %>
  </div>

<% end %>

app/views/brand_models/_brand_form.html.erb
<%= form_with url: brand_models_create_brand_path, method: :post do |form| %>

  <div class="field form-group col mb-4">
    <%= form.label :name, "Brand Name", class: "form-label" %>
    <%= form.text_field :name, placeholder: "Apple", class: "form-control" %>
  </div>
  <div class="action">
    <%= form.submit class: "btn btn-primary", value: "Create" %>
  </div>
  
<% end %>

app/views/brand_models/_model_edit_form.html.erb
<%= form_with url: brand_models_update_model_path, method: :post do |form| %>

  <div class="row mb-4">
    <div class="field form-group col">
      <%= form.label :id, "Old Model Name", class: "form-label" %>
      <%= form.grouped_collection_select :id, Brand.order(:name), :models, :name, :id, :name, {}, {class: "form-control"} %>
    </div>

    <div class="field form-group col">
      <%= form.label :new_name, "New Model Name", class: "form-label" %>
      <%= form.text_field :new_name, class: "form-control" %>
    </div>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-primary", value: "Save" %>
  </div>

<% end %>

app/views/brand_models/_model_form.html.erb
<%= form_with url: brand_models_create_model_path, method: :post do |form| %>

  <div class="row mb-4">
    <div class="field form-group col">
      <%= form.label :brand_id, class: "form-label" %>
      <%= form.collection_select :brand_id, Brand.order(:name), :id, :name, {}, {class: "form-control"} %>
    </div>

    <div class="field form-group col">
      <%= form.label :name, "Model Name", class: "form-label" %>
      <%= form.text_field :name, placeholder: "iPhone X", class: "form-control" %>
    </div>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-primary", value: "Create" %>
  </div>

<% end %>