config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'inventories#index'
  devise_for :accounts
  resources :inventories
  resources :brands, only: %i[index destroy]
  resources :models, only: [:destroy]
  post 'brands/create'
  patch 'brands/update'
  post 'models/create'
  patch 'models/update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
# frozen_string_literal: true

# Brand model mapped to Brands table in database
class Brand < ApplicationRecord
  has_many :models, dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/brands_controller.rb
# frozen_string_literal: true

# Controller for Brands views
class BrandsController < ApplicationController
  before_action :authenticate_account!
  before_action :authorize_account?, except: [:index]
  before_action :set_brand, only: %i[update destroy]

  def index
    @brands = Brand.order(:name)
  end

  def create # rubocop:disable Metrics/AbcSize
    @brand = Brand.new(name: params[:name])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brands_path, notice: 'New brand created successfully.' }
        format.json { render json: @brand, status: :ok }
      else
        format.html { redirect_to brands_path, alert: @brand.errors.full_messages }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def update # rubocop:disable Metrics/AbcSize
    respond_to do |format|
      if @brand.update(name: params[:new_name])
        format.html { redirect_to brands_path, notice: 'Brand name updated successfully.' }
        format.json { render json: @brand, status: :ok }
      else
        format.html { redirect_to brands_path, alert: @brand.errors.full_messages }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @brand.destroy
        format.html { redirect_to brands_path, notice: 'Brand deleted successfully.' }
        format.json { render json: {}, status: :ok }
      else
        format.html { redirect_to brands_path, alert: @brand.errors.full_messages }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def authorize_account?
    redirect_to brands_path, alert: 'You are not authorized.' unless current_account.manager?
  end

  def set_brand
    @brand = Brand.find(params[:id])
  end
end

app/views/brands/_create_form.html.erb
<%= form_with url: brands_create_path, method: :post do |form| %>

  <div class="field form-group col mb-4">
    <%= form.label :name, "Brand Name", class: "form-label" %>
    <%= form.text_field :name, placeholder: "Apple", required: true, class: "form-control" %>
  </div>
  <div class="action">
    <%= form.submit class: "btn btn-primary", value: "Create" %>
  </div>
  
<% end %>

app/views/brands/_edit_form.html.erb
<%= form_with url: brands_update_path, method: :patch do |form| %>

  <div class="row mb-4">
    <div class="field form-group col">
      <%= form.label :id, "Old Brand Name", class: "form-label" %>
      <%= form.collection_select :id, Brand.order(:name), :id, :name, {}, {class: "form-control"} %>
    </div>

    <div class="field form-group col">
      <%= form.label :new_name, "New Brand Name", class: "form-label" %>
      <%= form.text_field :new_name, required: true, class: "form-control" %>
    </div>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-primary", value: "Save" %>
  </div>

<% end %>

app/views/brands/index.html.erb
<div class="container">
  <div class="row row-cols-md-2 row-cols-1">

    <div id="accordion" class="col">
      <% @brands.each do |brand| %>
        <div class="card">
          <div class="card-header" id="heading<%= brand.id %>">
            <div class="d-flex justify-content-between align-items-center">
              <button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse<%= brand.id %>" aria-expanded="true" aria-controls="collapse<%= brand.id %>">
                <%= brand.name %>
              </button>
              <%= link_to "Destroy", brand, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger btn-sm" %>
            </div>
          </div>
          <div id="collapse<%= brand.id %>" class="collapse <%= 'show' if brand == @brands.first %>" aria-labelledby="heading<%= brand.id %>" data-parent="#accordion">
            <div class="card-body">
              <% brand.models.order(:name).each do |model| %>
                <div class="d-flex justify-content-between align-items-center">
                  <p><%= model.name %></p>
                  <%= link_to "Destroy", model, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-sm" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col">
      <div id="accordion">
        <div class="card">
          <div class="card-header" id="heading_1">
            <div class="d-flex justify-content-between align-items-center">
              <button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse_1" aria-expanded="true" aria-controls="collapse_1">
                <h4>Create new brand</h4>
              </button>
            </div>
          </div>

          <div id="collapse_1" class="collapse" aria-labelledby="heading_1" data-parent="#accordion">
            <div class="card-body">
              <%= render "brands/create_form" %>
            </div>
          </div>
        </div>
      </div>

      <div id="accordion">
        <div class="card">
          <div class="card-header" id="heading_2">
            <div class="d-flex justify-content-between align-items-center">
              <button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse_2" aria-expanded="true" aria-controls="collapse_2">
                <h4>Create new model</h4>
              </button>
            </div>
          </div>

          <div id="collapse_2" class="collapse" aria-labelledby="heading_2" data-parent="#accordion">
            <div class="card-body">
              <%= render "models/create_form" %>
            </div>
          </div>
        </div>
      </div>

      <div id="accordion">
        <div class="card">
          <div class="card-header" id="heading_3">
            <div class="d-flex justify-content-between align-items-center">
              <button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse_3" aria-expanded="true" aria-controls="collapse_3">
                <h4>Edit brand</h4>
              </button>
            </div>
          </div>

          <div id="collapse_3" class="collapse" aria-labelledby="heading_3" data-parent="#accordion">
            <div class="card-body">
              <%= render "brands/edit_form" %>
            </div>
          </div>
        </div>
      </div>

      <div id="accordion">
        <div class="card">
          <div class="card-header" id="heading_4">
            <div class="d-flex justify-content-between align-items-center">
              <button class="btn btn-link" data-bs-toggle="collapse" data-bs-target="#collapse_4" aria-expanded="true" aria-controls="collapse_4">
                <h4>Edit model</h4>
              </button>
            </div>
          </div>

          <div id="collapse_4" class="collapse" aria-labelledby="heading_4" data-parent="#accordion">
            <div class="card-body">
              <%= render "models/edit_form" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>