config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'inventories#index'
  devise_for :accounts
  resources :inventories
  resources :brands, only: %i[index destroy]
  resources :models, only: [:destroy]
  post 'brands/create'
  patch 'brands/update'
  post 'models/create'
  patch 'models/update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
	<div class="container-fluid">
		<%= link_to "My Inventory", root_path, class:"navbar-brand" %>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<%= link_to "New Inventory", new_inventory_path, class:"nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Brand/Model", brands_path, class:"nav-link" %>
				</li>
			</ul>
			
			<div class="d-flex"> 
				<% if account_signed_in? %>
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
						</li>
					</ul>
					<%= link_to "#{current_account.role.name}: #{current_account.name}", edit_account_registration_path, class: "nav-link text-white" %>
				<% else %>
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
						</li>
						<li class="nav-item">
							<%= link_to "Log In", new_account_session_path, class: "nav-link" %>
						</li>
					</ul>
				<% end %>
			</div>
		</div>
	</div>
</nav>

app/views/layouts/_notice.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Phone Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    
    <% if notice %>
      <%= render "layouts/notice" %>
    <% elsif alert %>
      <%= render "layouts/alert" %>
    <% end %>

    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag "autocomplete" %>
  </body>
</html>